import 'package:get/get.dart';

class AppTranslations extends Translations {
  // Basic fields
  static const String signUp = 'signUp';
  static const String name = 'name';
  static const String email = 'email';
  static const String mobile = 'mobile';
  static const String selectLanguage = 'selectLanguage';
  static const String selectCrops = 'selectCrops';
  static const String landSize = 'landSize';
  static const String profile = 'profile';
  static const String editProfile = 'editProfile';
  static const String location = 'location';
  static const String crops = 'crops';
  static const String language = 'language';
  static const String enterOtp = 'enterOtp';
  static const String continueText = 'continue';
  static const String alreadyHaveAccount = 'alreadyHaveAccount';
  static const String logIn = 'logIn';
  static const String activeFarmer = 'activeFarmer';
  static const String farmingOverview = 'farmingOverview';
  static const String totalCrops = 'totalCrops';

  // Additional keys for complete app functionality
  static const String error = 'error';
  static const String selectLanguageError = 'selectLanguageError';
  static const String selectCropError = 'selectCropError';
  static const String unableToDetectLocation = 'unableToDetectLocation';
  static const String otpError = 'otpError';
  static const String failedToSendOtp = 'failedToSendOtp';
  static const String signupFailed = 'signupFailed';
  static const String verifyDetailsAndTryAgain = 'verifyDetailsAndTryAgain';
  static const String invalidOtp = 'invalidOtp';
  static const String otpMustBe6Digits = 'otpMustBe6Digits';
  static const String registrationSuccessful = 'registrationSuccessful';
  static const String welcomeToGreengram = 'welcomeToGreengram';
  static const String enter = 'enter';
  static const String selectAtLeastOneCrop = 'selectAtLeastOneCrop';
  static const String failedToLoadUserDetails = 'failedToLoadUserDetails';
  static const String networkError = 'networkError';
  static const String profileUpdated = 'profileUpdated';
  static const String profileUpdatedSuccessfully = 'profileUpdatedSuccessfully';
  static const String updateFailed = 'updateFailed';
  static const String failedToUpdateProfile = 'failedToUpdateProfile';
  static const String updateError = 'updateError';
  static const String errorUpdatingProfile = 'errorUpdatingProfile';
  static const String locationServices = 'locationServices';
  static const String enableLocationServices = 'enableLocationServices';
  static const String locationPermission = 'locationPermission';
  static const String locationPermissionDenied = 'locationPermissionDenied';
  static const String locationPermissionsPermanentlyDenied = 'locationPermissionsPermanentlyDenied';
  static const String locationError = 'locationError';
  static const String couldNotGetCurrentLocation = 'couldNotGetCurrentLocation';
  static const String noUserDataAvailable = 'noUserDataAvailable';
  static const String cancel = 'cancel';
  static const String saveChanges = 'saveChanges';
  static const String changeProfilePicture = 'changeProfilePicture';
  static const String takePhoto = 'takePhoto';
  static const String chooseFromGallery = 'chooseFromGallery';
  static const String removePhoto = 'removePhoto';
  static const String camera = 'camera';
  static const String gallery = 'gallery';
  static const String removed = 'removed';
  static const String profilePictureRemoved = 'profilePictureRemoved';
  static const String cameraFunctionalityWillBeImplemented = 'cameraFunctionalityWillBeImplemented';
  static const String galleryFunctionalityWillBeImplemented = 'galleryFunctionalityWillBeImplemented';
  static const String userName = 'userName';
  static const String locationDisabled = 'locationDisabled';
  static const String permissionDenied = 'permissionDenied';
  static const String locationPermissionRequired = 'locationPermissionRequired';

  // Language code mapping
  static const Map<String, String> languageToCode = {
    'Assamese': 'as_IN',
    'Bengali': 'bn_IN',
    'Bodo': 'brx_IN',
    'Dogri': 'doi_IN',
    'Gujarati': 'gu_IN',
    'English': 'en_US',
    'Hindi': 'hi_IN',
    'Kannada': 'kn_IN',
    'Kashmiri': 'ks_IN',
    'Konkani': 'kok_IN',
    'Maithili': 'mai_IN',
    'Malayalam': 'ml_IN',
    'Manipuri': 'mni_IN',
    'Marathi': 'mr_IN',
    'Nepali': 'ne_IN',
    'Odia': 'or_IN',
    'Punjabi': 'pa_IN',
    'Sanskrit': 'sa_IN',
    'Santali': 'sat_IN',
    'Sindhi': 'sd_IN',
    'Tamil': 'ta_IN',
    'Telugu': 'te_IN',
    'Urdu': 'ur_IN'
  };

  @override
  Map<String, Map<String, String>> get keys => {
    // English
    'en_US': {
      signUp: 'Sign Up',
      name: 'Name',
      email: 'Email',
      mobile: 'Mobile',
      selectLanguage: 'Select Language',
      selectCrops: 'Select Crops',
      landSize: 'Land Size',
      profile: 'PROFILE',
      editProfile: 'Edit Profile',
      location: 'Location',
      crops: 'Crops',
      language: 'Language',
      enterOtp: 'Enter OTP',
      continueText: 'Continue',
      alreadyHaveAccount: 'Already have an account? ',
      logIn: 'Log In',
      activeFarmer: 'Active Farmer',
      farmingOverview: 'Farming Overview',
      totalCrops: 'Total Crops',
      error: 'Error',
      selectLanguageError: 'Please select a Language',
      selectCropError: 'Please select at least one Crop',
      unableToDetectLocation: 'Unable to detect location',
      otpError: 'OTP Error',
      failedToSendOtp: 'Failed to send OTP',
      signupFailed: 'Signup Failed',
      verifyDetailsAndTryAgain: 'Please verify details & try again',
      invalidOtp: 'Invalid OTP',
      otpMustBe6Digits: 'OTP must be 6 digits',
      registrationSuccessful: 'Registration Successful',
      welcomeToGreengram: 'Welcome to GREENGRAM!',
      enter: 'Enter',
      selectAtLeastOneCrop: 'Please select at least one crop',
      failedToLoadUserDetails: 'Failed to load user details',
      networkError: 'Network error',
      profileUpdated: 'Profile Updated',
      profileUpdatedSuccessfully: 'Your profile has been successfully updated with current location!',
      updateFailed: 'Update Failed',
      failedToUpdateProfile: 'Failed to update profile',
      updateError: 'Update Error',
      errorUpdatingProfile: 'Error updating profile',
      locationServices: 'Location Services',
      enableLocationServices: 'Please enable location services',
      locationPermission: 'Location Permission',
      locationPermissionDenied: 'Location permission denied',
      locationPermissionsPermanentlyDenied: 'Location permissions are permanently denied',
      locationError: 'Location Error',
      couldNotGetCurrentLocation: 'Could not get current location',
      noUserDataAvailable: 'No user data available',
      cancel: 'Cancel',
      saveChanges: 'Save Changes',
      changeProfilePicture: 'Change Profile Picture',
      takePhoto: 'Take Photo',
      chooseFromGallery: 'Choose from Gallery',
      removePhoto: 'Remove Photo',
      camera: 'Camera',
      gallery: 'Gallery',
      removed: 'Removed',
      profilePictureRemoved: 'Profile picture removed',
      cameraFunctionalityWillBeImplemented: 'Camera functionality will be implemented',
      galleryFunctionalityWillBeImplemented: 'Gallery functionality will be implemented',
      userName: 'User Name',
      locationDisabled: 'Location Disabled',
      permissionDenied: 'Permission Denied',
      locationPermissionRequired: 'Location permission is required',
    },

    // Hindi
    'hi_IN': {
      signUp: 'साइन अप करें',
      name: 'नाम',
      email: 'ईमेल',
      mobile: 'मोबाइल',
      selectLanguage: 'भाषा चुनें',
      selectCrops: 'फसलें चुनें',
      landSize: 'जमीन का आकार',
      profile: 'प्रोफ़ाइल',
      editProfile: 'प्रोफ़ाइल संपादित करें',
      location: 'स्थान',
      crops: 'फसलें',
      language: 'भाषा',
      enterOtp: 'ओटीपी दर्ज करें',
      continueText: 'जारी रखें',
      alreadyHaveAccount: 'क्या आपका खाता पहले से है? ',
      logIn: 'लॉग इन',
      activeFarmer: 'सक्रिय किसान',
      farmingOverview: 'खेती का अवलोकन',
      totalCrops: 'कुल फसलें',
      error: 'त्रुटि',
      selectLanguageError: 'कृपया एक भाषा चुनें',
      selectCropError: 'कृपया कम से कम एक फसल चुनें',
      unableToDetectLocation: 'स्थान का पता लगाने में असमर्थ',
      otpError: 'ओटीपी त्रुटि',
      failedToSendOtp: 'ओटीपी भेजने में विफल',
      signupFailed: 'साइनअप विफल',
      verifyDetailsAndTryAgain: 'कृपया विवरण सत्यापित करें और पुनः प्रयास करें',
      invalidOtp: 'अमान्य ओटीपी',
      otpMustBe6Digits: 'ओटीपी 6 अंकों का होना चाहिए',
      registrationSuccessful: 'पंजीकरण सफल',
      welcomeToGreengram: 'ग्रीनग्राम में आपका स्वागत है!',
      enter: 'दर्ज करें',
      selectAtLeastOneCrop: 'कृपया कम से कम एक फसल चुनें',
      failedToLoadUserDetails: 'उपयोगकर्ता विवरण लोड करने में विफल',
      networkError: 'नेटवर्क त्रुटि',
      profileUpdated: 'प्रोफ़ाइल अपडेट किया गया',
      profileUpdatedSuccessfully: 'आपकी प्रोफ़ाइल वर्तमान स्थान के साथ सफलतापूर्वक अपडेट की गई है!',
      updateFailed: 'अपडेट विफल',
      failedToUpdateProfile: 'प्रोफ़ाइल अपडेट करने में विफल',
      updateError: 'अपडेट त्रुटि',
      errorUpdatingProfile: 'प्रोफ़ाइल अपडेट करने में त्रुटि',
      locationServices: 'स्थान सेवाएं',
      enableLocationServices: 'कृपया स्थान सेवाएं सक्षम करें',
      locationPermission: 'स्थान अनुमति',
      locationPermissionDenied: 'स्थान अनुमति अस्वीकृत',
      locationPermissionsPermanentlyDenied: 'स्थान अनुमतियां स्थायी रूप से अस्वीकृत हैं',
      locationError: 'स्थान त्रुटि',
      couldNotGetCurrentLocation: 'वर्तमान स्थान प्राप्त नहीं कर सका',
      noUserDataAvailable: 'कोई उपयोगकर्ता डेटा उपलब्ध नहीं',
      cancel: 'रद्द करें',
      saveChanges: 'परिवर्तन सहेजें',
      changeProfilePicture: 'प्रोफ़ाइल चित्र बदलें',
      takePhoto: 'फोटो लें',
      chooseFromGallery: 'गैलरी से चुनें',
      removePhoto: 'फोटो हटाएं',
      camera: 'कैमरा',
      gallery: 'गैलरी',
      removed: 'हटाया गया',
      profilePictureRemoved: 'प्रोफ़ाइल चित्र हटाया गया',
      cameraFunctionalityWillBeImplemented: 'कैमरा कार्यक्षमता लागू की जाएगी',
      galleryFunctionalityWillBeImplemented: 'गैलरी कार्यक्षमता लागू की जाएगी',
      userName: 'उपयोगकर्ता नाम',
      locationDisabled: 'स्थान अक्षम',
      permissionDenied: 'अनुमति अस्वीकृत',
      locationPermissionRequired: 'स्थान अनुमति आवश्यक है',
    },

    // Tamil
    'ta_IN': {
      signUp: 'பதிவு செய்யுங்கள்',
      name: 'பெயர்',
      email: 'மின்னஞ்சல்',
      mobile: 'மொபைல்',
      selectLanguage: 'மொழி தேர்வு செய்யுங்கள்',
      selectCrops: 'பயிர்களை தேர்வு செய்யுங்கள்',
      landSize: 'நிலத்தின் அளவு',
      profile: 'சுயவிவரம்',
      editProfile: 'சுயவிவரத்தை திருத்து',
      location: 'இடம்',
      crops: 'பயிர்கள்',
      language: 'மொழி',
      enterOtp: 'OTP உள்ளிடுங்கள்',
      continueText: 'தொடர்க',
      alreadyHaveAccount: 'ஏற்கனவே கணக்கு உள்ளதா? ',
      logIn: 'உள்நுழை',
      activeFarmer: 'செயலில் உள்ள விவசாயி',
      farmingOverview: 'விவசாய மேலோட்டம்',
      totalCrops: 'மொத்த பயிர்கள்',
      error: 'பிழை',
      selectLanguageError: 'தயவுசெய்து ஒரு மொழியைத் தேர்ந்தெடுக்கவும்',
      selectCropError: 'தயவுசெய்து குறைந்தது ஒரு பயிரைத் தேர்ந்தெடுக்கவும்',
      unableToDetectLocation: 'இருப்பிடத்தைக் கண்டறிய முடியவில்லை',
      otpError: 'OTP பிழை',
      failedToSendOtp: 'OTP அனுப்புவதில் தோல்வி',
      signupFailed: 'பதிவு தோல்வியடைந்தது',
      verifyDetailsAndTryAgain: 'தயவுசெய்து விவரங்களைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்',
      invalidOtp: 'தவறான OTP',
      otpMustBe6Digits: 'OTP 6 இலக்கங்களாக இருக்க வேண்டும்',
      registrationSuccessful: 'பதிவு வெற்றிகரமானது',
      welcomeToGreengram: 'க்ரீன்கிராமில் உங்களை வரவேற்கிறோம்!',
      enter: 'உள்ளிடவும்',
      selectAtLeastOneCrop: 'தயவுசெய்து குறைந்தது ஒரு பயிரைத் தேர்ந்தெடுக்கவும்',
      failedToLoadUserDetails: 'பயனர் விவரங்களை ஏற்றுவதில் தோல்வி',
      networkError: 'நெட்வொர்க் பிழை',
      profileUpdated: 'சுயவிவரம் புதுப்பிக்கப்பட்டது',
      profileUpdatedSuccessfully: 'உங்கள் சுயவிவரம் தற்போதைய இருப்பிடத்துடன் வெற்றிகரமாகப் புதுப்பிக்கப்பட்டது!',
      updateFailed: 'புதுப்பிப்பு தோல்வியடைந்தது',
      failedToUpdateProfile: 'சுயவிவரத்தைப் புதுப்பிப்பதில் தோல்வி',
      updateError: 'புதுப்பிப்பு பிழை',
      errorUpdatingProfile: 'சுயவிவரத்தைப் புதுப்பிப்பதில் பிழை',
      locationServices: 'இருப்பிட சேவைகள்',
      enableLocationServices: 'தயவுசெய்து இருப்பிட சேவைகளை இயக்கவும்',
      locationPermission: 'இருப்பிட அனுமதி',
      locationPermissionDenied: 'இருப்பிட அனுமதி மறுக்கப்பட்டது',
      locationPermissionsPermanentlyDenied: 'இருப்பிட அனுமதிகள் நிரந்தரமாக மறுக்கப்பட்டுள்ளன',
      locationError: 'இருப்பிட பிழை',
      couldNotGetCurrentLocation: 'தற்போதைய இருப்பிடத்தைப் பெற முடியவில்லை',
      noUserDataAvailable: 'பயனர் தரவு எதுவும் கிடைக்கவில்லை',
      cancel: 'ரத்துசெய்',
      saveChanges: 'மாற்றங்களைச் சேமி',
      changeProfilePicture: 'சுயவிவர படத்தை மாற்று',
      takePhoto: 'புகைப்படம் எடு',
      chooseFromGallery: 'கேலரியிலிருந்து தேர்வுசெய்',
      removePhoto: 'படத்தை அகற்று',
      camera: 'கேமரா',
      gallery: 'கேலரி',
      removed: 'அகற்றப்பட்டது',
      profilePictureRemoved: 'சுயவிவர படம் அகற்றப்பட்டது',
      cameraFunctionalityWillBeImplemented: 'கேமரா செயல்பாடு செயல்படுத்தப்படும்',
      galleryFunctionalityWillBeImplemented: 'கேலரி செயல்பாடு செயல்படுத்தப்படும்',
      userName: 'பயனர் பெயர்',
      locationDisabled: 'இருப்பிடம் முடக்கப்பட்டது',
      permissionDenied: 'அனுமதி மறுக்கப்பட்டது',
      locationPermissionRequired: 'இருப்பிட அனுமதி தேவை',
    },

    // Telugu
    'te_IN': {
      signUp: 'సైన్ అప్',
      name: 'పేరు',
      email: 'ఇమెయిల్',
      mobile: 'మొబైల్',
      selectLanguage: 'భాష ఎంచుకోండి',
      selectCrops: 'పంటలను ఎంచుకోండి',
      landSize: 'భూమి పరిమాణం',
      profile: 'ప్రొఫైల్',
      editProfile: 'ప్రొఫైల్ సవరించండి',
      location: 'స్థానం',
      crops: 'పంటలు',
      language: 'భాష',
      enterOtp: 'OTP నమోదు చేయండి',
      continueText: 'కొనసాగించు',
      alreadyHaveAccount: 'ఇప్పటికే ఖాతా ఉందా? ',
      logIn: 'లాగిన్',
      activeFarmer: 'క్రియాశీల రైతు',
      farmingOverview: 'వ్యవసాయ అవలోకనం',
      totalCrops: 'మొత్తం పంటలు',
      error: 'లోపం',
      selectLanguageError: 'దయచేసి ఒక భాష ఎంచుకోండి',
      selectCropError: 'దయచేసి కనీసం ఒక పంట ఎంచుకోండి',
      unableToDetectLocation: 'స్థానాన్ని గుర్తించలేకపోయింది',
      otpError: 'OTP లోపం',
      failedToSendOtp: 'OTP పంపడంలో విఫలమైంది',
      signupFailed: 'సైనప్ విఫలమైంది',
      verifyDetailsAndTryAgain: 'దయచేసి వివరాలను ధృవీకరించి మళ్లీ ప్రయత్నించండి',
      invalidOtp: 'చెల్లని OTP',
      otpMustBe6Digits: 'OTP 6 అంకెలు ఉండాలి',
      registrationSuccessful: 'నమోదు విజయవంతమైంది',
      welcomeToGreengram: 'గ్రీన్‌గ్రామ్‌కు స్వాగతం!',
      enter: 'నమోదు చేయండి',
      selectAtLeastOneCrop: 'దయచేసి కనీసం ఒక పంట ఎంచుకోండి',
      failedToLoadUserDetails: 'వినియోగదారు వివరాలను లోడ్ చేయడంలో విఫలమైంది',
      networkError: 'నెట్‌వర్క్ లోపం',
      profileUpdated: 'ప్రొఫైల్ అప్‌డేట్ చేయబడింది',
      profileUpdatedSuccessfully: 'మీ ప్రొఫైల్ ప్రస్తుత స్థానంతో విజయవంతంగా అప్‌డేట్ చేయబడింది!',
      updateFailed: 'అప్‌డేట్ విఫలమైంది',
      failedToUpdateProfile: 'ప్రొఫైల్‌ను అప్‌డేట్ చేయడంలో విఫలమైంది',
      updateError: 'అప్‌డేట్ లోపం',
      errorUpdatingProfile: 'ప్రొఫైల్‌ను అప్‌డేట్ చేయడంలో లోపం',
      locationServices: 'స్థాన సేవలు',
      enableLocationServices: 'దయచేసి స్థాన సేవలను ప్రారంభించండి',
      locationPermission: 'స్థాన అనుమతి',
      locationPermissionDenied: 'స్థాన అనుమతి తిరస్కరించబడింది',
      locationPermissionsPermanentlyDenied: 'స్థాన అనుమతులు శాశ్వతంగా తిరస్కరించబడ్డాయి',
      locationError: 'స్థాన లోపం',
      couldNotGetCurrentLocation: 'ప్రస్తుత స్థానాన్ని పొందలేకపోయింది',
      noUserDataAvailable: 'వినియోగదారు డేటా అందుబాటులో లేదు',
      cancel: 'రద్దుచేయి',
      saveChanges: 'మార్పులను సేవ్ చేయండి',
      changeProfilePicture: 'ప్రొఫైల్ చిత్రాన్ని మార్చండి',
      takePhoto: 'ఫోటో తీయండి',
      chooseFromGallery: 'గ్యాలరీ నుండి ఎంచుకోండి',
      removePhoto: 'ఫోటోను తీసివేయండి',
      camera: 'కెమెరా',
      gallery: 'గ్యాలరీ',
      removed: 'తీసివేయబడింది',
      profilePictureRemoved: 'ప్రొఫైల్ చిత్రం తీసివేయబడింది',
      cameraFunctionalityWillBeImplemented: 'కెమెరా కార్యాచరణ అమలు చేయబడుతుంది',
      galleryFunctionalityWillBeImplemented: 'గ్యాలరీ కార్యాచరణ అమలు చేయబడుతుంది',
      userName: 'వినియోగదారు పేరు',
      locationDisabled: 'స్థానం నిలిపివేయబడింది',
      permissionDenied: 'అనుమతి తిరస్కరించబడింది',
      locationPermissionRequired: 'స్థాన అనుమతి అవసరం',
    },

    // Bengali
    'bn_IN': {
      signUp: 'সাইন আপ করুন',
      name: 'নাম',
      email: 'ইমেইল',
      mobile: 'মোবাইল',
      selectLanguage: 'ভাষা নির্বাচন করুন',
      selectCrops: 'ফসল নির্বাচন করুন',
      landSize: 'জমির আকার',
      profile: 'প্রোফাইল',
      editProfile: 'প্রোফাইল সম্পাদনা',
      location: 'অবস্থান',
      crops: 'ফসল',
      language: 'ভাষা',
      enterOtp: 'OTP প্রবেশ করুন',
      continueText: 'চালিয়ে যান',
      alreadyHaveAccount: 'ইতিমধ্যে অ্যাকাউন্ট আছে? ',
      logIn: 'লগ ইন',
      activeFarmer: 'সক্রিয় কৃষক',
      farmingOverview: 'কৃষি সংক্ষিপ্তসার',
      totalCrops: 'মোট ফসল',
      error: 'ত্রুটি',
      selectLanguageError: 'দয়া করে একটি ভাষা নির্বাচন করুন',
      selectCropError: 'দয়া করে কমপক্ষে একটি ফসল নির্বাচন করুন',
      unableToDetectLocation: 'অবস্থান সনাক্ত করতে অক্ষম',
      otpError: 'OTP ত্রুটি',
      failedToSendOtp: 'OTP পাঠাতে ব্যর্থ',
      signupFailed: 'সাইনআপ ব্যর্থ',
      verifyDetailsAndTryAgain: 'দয়া করে বিবরণ যাচাই করুন এবং আবার চেষ্টা করুন',
      invalidOtp: 'অবৈধ OTP',
      otpMustBe6Digits: 'OTP ৬ ডিজিটের হতে হবে',
      registrationSuccessful: 'নিবন্ধন সফল',
      welcomeToGreengram: 'গ্রীনগ্রামে স্বাগতম!',
      enter: 'প্রবেশ করুন',
      selectAtLeastOneCrop: 'দয়া করে কমপক্ষে একটি ফসল নির্বাচন করুন',
      failedToLoadUserDetails: 'ব্যবহারকারীর বিবরণ লোড করতে ব্যর্থ',
      networkError: 'নেটওয়ার্ক ত্রুটি',
      profileUpdated: 'প্রোফাইল আপডেট করা হয়েছে',
      profileUpdatedSuccessfully: 'আপনার প্রোফাইল বর্তমান অবস্থানের সাথে সফলভাবে আপডেট করা হয়েছে!',
      updateFailed: 'আপডেট ব্যর্থ',
      failedToUpdateProfile: 'প্রোফাইল আপডেট করতে ব্যর্থ',
      updateError: 'আপডেট ত্রুটি',
      errorUpdatingProfile: 'প্রোফাইল আপডেট করতে ত্রুটি',
      locationServices: 'অবস্থান সেবা',
      enableLocationServices: 'দয়া করে অবস্থান সেবা চালু করুন',
      locationPermission: 'অবস্থান অনুমতি',
      locationPermissionDenied: 'অবস্থান অনুমতি প্রত্যাখ্যাত',
      locationPermissionsPermanentlyDenied: 'অবস্থান অনুমতি স্থায়ীভাবে প্রত্যাখ্যাত',
      locationError: 'অবস্থান ত্রুটি',
      couldNotGetCurrentLocation: 'বর্তমান অবস্থান পেতে পারেনি',
      noUserDataAvailable: 'কোন ব্যবহারকারী ডেটা উপলব্ধ নেই',
      cancel: 'বাতিল',
      saveChanges: 'পরিবর্তন সংরক্ষণ করুন',
      changeProfilePicture: 'প্রোফাইল ছবি পরিবর্তন করুন',
      takePhoto: 'ছবি তুলুন',
      chooseFromGallery: 'গ্যালারি থেকে নির্বাচন করুন',
      removePhoto: 'ছবি সরান',
      camera: 'ক্যামেরা',
      gallery: 'গ্যালারি',
      removed: 'সরানো হয়েছে',
      profilePictureRemoved: 'প্রোফাইল ছবি সরানো হয়েছে',
      cameraFunctionalityWillBeImplemented: 'ক্যামেরা কার্যকারিতা বাস্তবায়িত হবে',
      galleryFunctionalityWillBeImplemented: 'গ্যালারি কার্যকারিতা বাস্তবায়িত হবে',
      userName: 'ব্যবহারকারীর নাম',
      locationDisabled: 'অবস্থান নিষ্ক্রিয়',
      permissionDenied: 'অনুমতি প্রত্যাখ্যাত',
      locationPermissionRequired: 'অবস্থান অনুমতি প্রয়োজন',
    },

    // Gujarati
    'gu_IN': {
      signUp: 'સાઇન અપ કરો',
      name: 'નામ',
      email: 'ઇમેઇલ',
      mobile: 'મોબાઇલ',
      selectLanguage: 'ભાષા પસંદ કરો',
      selectCrops: 'પાક પસંદ કરો',
      landSize: 'જમીનનું કદ',
      profile: 'પ્રોફાઇલ',
      editProfile: 'પ્રોફાઇલ સંપાદિત કરો',
      location: 'સ્થાન',
      crops: 'પાક',
      language: 'ભાષા',
      enterOtp: 'OTP દાખલ કરો',
      continueText: 'ચાલુ રાખો',
      alreadyHaveAccount: 'પહેલેથી એકાઉન્ટ છે? ',
      logIn: 'લૉગ ઇન',
      activeFarmer: 'સક્રિય ખેડૂત',
      farmingOverview: 'ખેતીની ઝાંખી',
      totalCrops: 'કુલ પાક',
      error: 'ભૂલ',
      selectLanguageError: 'કૃપા કરીને ભાષા પસંદ કરો',
      selectCropError: 'કૃપા કરીને ઓછામાં ઓછો એક પાક પસંદ કરો',
      unableToDetectLocation: 'સ્થાન શોધી શકાતું નથી',
      otpError: 'OTP ભૂલ',
      failedToSendOtp: 'OTP મોકલવામાં નિષ્ફળ',
      signupFailed: 'સાઇનઅપ નિષ્ફળ',
      verifyDetailsAndTryAgain: 'કૃપા કરીને વિગતો ચકાસો અને ફરી પ્રયાસ કરો',
      invalidOtp: 'અમાન્ય OTP',
      otpMustBe6Digits: 'OTP 6 અંકનો હોવો જોઇએ',
      registrationSuccessful: 'નોંધણી સફળ',
      welcomeToGreengram: 'ગ્રીનગ્રામમાં આપનું સ્વાગત છે!',
      enter: 'દાખલ કરો',
      selectAtLeastOneCrop: 'કૃપા કરીને ઓછામાં ઓછો એક પાક પસંદ કરો',
      failedToLoadUserDetails: 'વપરાશકર્તાની વિગતો લોડ કરવામાં નિષ્ફળ',
      networkError: 'નેટવર્ક ભૂલ',
      profileUpdated: 'પ્રોફાઇલ અપડેટ થયું',
      profileUpdatedSuccessfully: 'તમારી પ્રોફાઇલ વર્તમાન સ્થાન સાથે સફળતાપૂર્વક અપડેટ થઈ છે!',
      updateFailed: 'અપડેટ નિષ્ફળ',
      failedToUpdateProfile: 'પ્રોફાઇલ અપડેટ કરવામાં નિષ્ફળ',
      updateError: 'અપડેટ ભૂલ',
      errorUpdatingProfile: 'પ્રોફાઇલ અપડેટ કરવામાં ભૂલ',
      locationServices: 'સ્થાન સેવાઓ',
      enableLocationServices: 'કૃપા કરીને સ્થાન સેવાઓ સક્ષમ કરો',
      locationPermission: 'સ્થાન પરવાનગી',
      locationPermissionDenied: 'સ્થાન પરવાનગી નકારવામાં આવી',
      locationPermissionsPermanentlyDenied: 'સ્થાન પરવાનગીઓ કાયમ માટે નકારવામાં આવી છે',
      locationError: 'સ્થાન ભૂલ',
      couldNotGetCurrentLocation: 'વર્તમાન સ્થાન મેળવી શકાયું નથી',
      noUserDataAvailable: 'કોઈ વપરાશકર્તા ડેટા ઉપલબ્ધ નથી',
      cancel: 'રદ કરો',
      saveChanges: 'ફેરફારો સાચવો',
      changeProfilePicture: 'પ્રોફાઇલ ચિત્ર બદલો',
      takePhoto: 'ફોટો લો',
      chooseFromGallery: 'ગેલેરીમાંથી પસંદ કરો',
      removePhoto: 'ફોટો દૂર કરો',
      camera: 'કેમેરા',
      gallery: 'ગેલેરી',
      removed: 'દૂર કર્યું',
      profilePictureRemoved: 'પ્રોફાઇલ ચિત્ર દૂર કર્યું',
      cameraFunctionalityWillBeImplemented: 'કેમેરા કાર્યક્ષમતા અમલમાં આવશે',
      galleryFunctionalityWillBeImplemented: 'ગેલેરી કાર્યક્ષમતા અમલમાં આવશે',
      userName: 'વપરાશકર્તા નામ',
      locationDisabled: 'સ્થાન નિષ્ક્રિય',
      permissionDenied: 'પરવાનગી નકારવામાં આવી',
      locationPermissionRequired: 'સ્થાન પરવાનગી જરૂરી છે',
    },

    // Add more languages as needed...
  };
}
